wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.21
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.13
    t:
      1:
      - 5
      2:
      - 5
      4: 3.8.13
      5: 0.10.21
      8:
      - 5
criterion:
  desc: null
  value: mae
max_depth:
  desc: null
  value: 15
max_features:
  desc: null
  value: 0.5
max_tfidf_features:
  desc: null
  value: 5
min_samples_leaf:
  desc: null
  value: 3
min_samples_split:
  desc: null
  value: 4
n_estimators:
  desc: null
  value: 100
n_jobs:
  desc: null
  value: -1
oob_score:
  desc: null
  value: true
output_artifact:
  desc: null
  value: random_forest_export
random_seed:
  desc: null
  value: 42
rf_config:
  desc: null
  value: /Users/zhas/Desktop/MLOps/udacity-mlops/nd0821-c2-build-model-workflow-starter/outputs/2022-05-02/16-50-04/rf_config.json
stratify_by:
  desc: null
  value: neighbourhood_group
trainval_artifact:
  desc: null
  value: trainval_data.csv:latest
val_size:
  desc: null
  value: 0.2
