wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.15
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.8.5
    session_history: code/_session_history.ipynb
    start_time: 1651482938
    t:
      1:
      - 55
      2:
      - 53
      - 55
      3:
      - 2
      4: 3.8.5
      5: 0.12.15
      8:
      - 1
      - 2
      - 5
