wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.15
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.8.5
    start_time: 1651485808
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 24
      4: 3.8.5
      5: 0.12.15
      8:
      - 2
      - 5
